[logging]
# see https://docs.python.org/3/library/logging.html#logging-levels
log_level = WARNING

[api]
must be in range 1025-65535
port = 8000

[pressure_control]
# in seconds, default is 0.01
cycle_time = 0.01
# in mbar, must be within 0.0 - 50.0
tolerance_plus = 0.0
# in mbar, must be within 0.0 - 50.0
tolerance_minus = 10.0
# default pressure setpoint in mbar
setpoint = 962.9274
# maximum allowed pressure in mbar
pressure_max = 1084.0
# minimum allowed pressure in mbar
pressure_min = 450.0

[pressure_sensor]
# in seconds, default is 0.01
cycle_time = 0.01
# RPi only has 0 or 1, always use 1, unless you absolutly know what you are doing
smbus_nr = 1
# I2C address range is  0x00-0x7f, BMP280 typically 0x76 or 0x77, default 0x76
i2c_address = 0x76

[pump_control]
# in seconds, default is 0.5
cycle_time = 0.5
# to which GPIO pin MOSFET for switching pump is connected to, default is 24
pin_number = 24

[valve_control]
# in seconds, default is 0.01
cycle_time = 0.01
# to which GPIO pin MOSFET for switching valve is connected to, default is 23
pin_number = 23

[mode_hold]
# in mbar
pressure_target = 875.0

[mode_interval]
# peak pressure target in mbar
peak_pressure = 790.0
# interval time in seconds
interval_time = 20.0

[mode_pulsating]
# pump time in seconds
pump_time = 2.7
# release time in seconds
release_time = 1.7